### ISSUE TITLE
Readme is not clear

### ISSUE THREAD

**Issue by Jacinto27** [Amuyea-gbatemp/Shin-Megami-Tensei-III-Nocturne-HD-EN-JP-Save-Editor#1]
What exactly should I rewrite the py file into, and what version number am I suppoused ot look at, sorry if answered already.

**Comment by Amuyea-gbatemp** [comment]
Install Python at https://www.python.org/downloads/
Select python for your OS. In the installer be sure the box Add Python (Version) to PATH is ticked.
(3.10 for this guide) 
Click customize install and check that all the boxes are ticked on this page.
Click Next and tick Install for all Users.
Click Install. Wait and Python should install correctly. Reboot.

PyQt5:
 
On Windows, open a Command prompt. (Windows Key + R at the same time. Type cmd. Press enter). Type the following.
 
`pip Install PyQt5`

 Press enter and allow it to install. All the prerequisites should be installed.
 
 Pip not installed with Python (Windows):
 If Pip wasn't recognized as a command after a reboot, follow these steps.
 Go to https://pip.pypa.io/en/stable/installation/
 Right-click the script 
 https://bootstrap.pypa.io/get-pip.py
 and save link as/save linked content as.
 Make a new folder in Desktop and save it there.
 Go to the new folder.
 If done correctly so far you should be able to double click 
Get-pip.py

Let the installer do its job and you should now have Pip to be able to install PyQt5 again.

If double-clicking doesn't work, click the bar at the top with the folders, between the up arrow and the refresh (circular arrow)
Type 
`cmd`
Press enter.
Type 
`py Get-pip.py`

Let the installer install pip. Attempt PyQt5 again. 


Download the releases atm (1.0.0)
Open Terminal in the folder, and run `pip install -r requirements.txt`

Finally, you can run the program with `python3 Shin.py` or Right-click the Shin.py

**Comment by Jacinto27** [comment]
Thanks, very informative, you should consider adding these parts to the readme of the project: 

Verify installation of PyQt5

Open Terminal in the folder, and run pip install -r requirements.txt

You can run the program with python**Version#** Shin.py or Right-click the Shin.py (the part that explains this in the readme is not clear enough.)

Will try this later, but now im sure it'll work.
